### ISSUE TITLE
Add a new pygamelib.engine.ExtendableBoard object to support chunks

### ISSUE THREAD

**Issue by arnauddupuis** [pygamelib/pygamelib#213]
**Problem summary/missing feature:**  
The Board object, while handy, is not very optimized. It is one single 2.5D array and the bigger it becomes the slower it is. `partial display` alleviate the performance issue but it is not the best way of doing things.

It also makes it very difficult to dynamically expand a board.

**Expected behavior:**  
It would be nice for a Board to have a chunk system where the 2.5D arrays are contained. It would also make adding and discarding chunks very easy.

**Work to do:**  
Here are my initial thoughts on what to do for this to work (all of this is up for discussion):

 - Create a new class in `pygamelib.engine`: ExtendableBoard (or StechableBoard or MalleableBoard, pick the best name you can think about). This object should be able to have the following constructor parameters:
    - max_width: int: to limit the maximum width expansion.
    - max_height: int: to limit the maximum height expansion.
    - screen_width: int: The width when drawn on the screen (not all chunks are going to be drawn at all time, that's the point). Name is up for debate.
    - screen_height: int: The height when drawn on the screen (not all chunks are going to be drawn at all time, that's the point). Name is up for debate.
    - extend_strategy: that can be `pygamelib.constants.HORIZONTAL_EXTEND` or `pygamelib.constants.VERTICAL_EXTEND` (add the constants to the `constants` module. Horizontal means that it will be filled row by row and vertical column by column (unless a specific chunk is specified).
    - discard_strategy: that can be DOF_STRATEGY (Discard Older First which means that we need to know who is the older), DNF_STRATEGY (Discard Newer First), DFF_STRATEGY (Discard Furthest First, the furthest according to the euclidian distance is discarded first), DCF_STRATEGY (Discard Closest First).
    - chunks: a 2D array of Board objects, it will initialize the ExtendableBoard with chunks. Positions are taken straight from the 
 - create a dict `ExtendableBoard._chunks` that will hold the chunks (a single chunk being a `pygamelib.engine.Board` object). This should be indexed using the chunk position in the chunk map using a tuple: `(row, column)`. Indexing should start by default at (0, 0).
 - Add API: `ExtendableBoard.add_chunks(board: pygamelib.engine.Board, chunk_row: Optional(int), chunk_column: Optional(int)) -> bool`: Add a chunk to the ExtendableBoard. If no chunk row and column are specified extend the chunk according to `extend_strategy`.
 - Add API: `ExtendableBoard.discard_chunks(chunk_row: Optional(int), chunk_column: Optional(int)) -> bool`: discard the chunk at this coordinate (put the dict to None).
 - Add API: `ExtendableBoard.discard_chunks(board: pygamelib.engine.Board) -> bool` : find object in chunk map and discard it.
 - Add API: `render_to_buffer(self, buffer, row, column, buffer_height, buffer_width) -> None`: render the ExtendableBoard on screen according to screen and ExtendableBoard constraints.
 - Wrap the `pygamelib.engine.Board` features that are used by `pygamelib.engine.Game` to allow for a drop in replacement of a `Board` by an ExtandableBoard.

We probably also need some property that hold the current `position` in the ExtendableBoard (what are the chunks that are currently displayed). This may (or may not) raise a discussion about the object that goes into the extendable board. Could it be a new wrapping class around Board, that holds some of the needed attributes (like the visibility, time of insertion, etc.).

**Comment by DamyanBG** [comment]
Hello, this task sounds interesting. You can assign it to me !

**Comment by arnauddupuis** [comment]
Done! Yes it is. 
I'm not sure that it is obvious in the definition of the problem but my idea is that we can use ExtendableBoard or Board in `engine.Game`. So that means that it should be usable like a Board in methods like `Game.insert_board`, `Game.get_board`, `Game.change_level`, etc. That includes serialization and saving.
You can drop on [Discord](https://discord.gg/ZtVaMqr) if you need help and/or bounce ideas (or do that in the comments obviously :grin: )

**Comment by DamyanBG** [comment]
Hello, 

I was sick for few days and I will start work on that on Monday, sorry for the delay.

**Comment by arnauddupuis** [comment]
No worries at all! We do this for fun, there's no deadline and no pressure.
This is a sort of game engine in the terminal, I think the world will survive if we take our time :rofl:

**Comment by DamyanBG** [comment]
I tried to configure my environment, but this pipenv gives me hard time. I am using Windows machine, I pull the last code, create new virtual env and inside this virtual env I write:
- pip install pipenv
- pipenv install --dev
- pipenv shell
And after that I am trying to execute the unittest without success with errors, related to missing packages....

**Comment by arnauddupuis** [comment]
can you show the output of the tests, please? It is entirely possible that we have an issue in the dependencies.

**Comment by DamyanBG** [comment]
======================================================================
ERROR: test_animation (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_animation
Traceback (most recent call last):
  File "C:\Users\death\AppData\Local\Programs\Python\Python310\lib\unittest\loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "C:\Users\death\AppData\Local\Programs\Python\Python310\lib\unittest\loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "C:\Users\death\OneDrive\Работен плот\Development\Contribution\NewPyGameLib\pygamelib\tests\test_animation.py", line 1, in <module>
    import pygamelib.gfx.core as gfx_core
  File "C:\Users\death\OneDrive\Работен плот\Development\Contribution\NewPyGameLib\pygamelib\pygamelib\gfx\core.py", line 15, in <module>
    from pygamelib import base
  File "C:\Users\death\OneDrive\Работен плот\Development\Contribution\NewPyGameLib\pygamelib\pygamelib\base.py", line 29, in <module>
    from blessed import Terminal
  File "C:\Users\death\.virtualenvs\pygamelib-ar0VhyVh\lib\site-packages\blessed\__init__.py", line 12, in <module>
    from blessed.win_terminal import Terminal
  File "C:\Users\death\.virtualenvs\pygamelib-ar0VhyVh\lib\site-packages\blessed\win_terminal.py", line 12, in <module>
    from jinxed import win32  # pylint: disable=import-error
ModuleNotFoundError: No module named 'jinxed'

**Comment by DamyanBG** [comment]
There are a lot of errors connected with this module.

But - let me describe what I am doing first and is it correct:

- I am using Windows machine with Python 3.10.5
- I installed pipenv to my global packages with pip install pipenv
- I made new pipenv virtual env with pipenv shell
- after that I executed pipenv install --dev
- then I am running the command for the tests.

**Comment by arnauddupuis** [comment]
oh... that's a dependency's dependency... jinxed is required by blessed, maybe there's an issue with the blessed requirements. The requirements.txt file from blessed is available here: https://github.com/jquast/blessed/blob/master/requirements.txt and it does have the jinxed requirement for windows.

Here's what I'm suggesting:
 1. start your python interpreter.
 2. import platform
 3. print(platform.system())
 4. from blessed import Terminal

Here you should see your error. It would be useful to report that to the blessed team (if it is not yet reported).

In the meantime, manually install jinxed with `pip install jinxed`. I'll add that to my release TODO list to make sure to check that this bug is fixed or to force the jinxed dependency.

**Comment by DamyanBG** [comment]
The problem was in my computer. I tried to use > pipenv run python -m unittest discover -s tests and it works. I will start work on the task.
